# Generated by Django 3.2.6 on 2021-08-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Вид услуги')),
                ('text', models.TextField(null=True, verbose_name='Описание')),
                ('file', models.FileField(null=True, upload_to='', verbose_name='Памятка')),
            ],
        ),
    ]
